// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.646
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func addTodoClick() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_addTodoClick_30db`,
		Function: `function __templ_addTodoClick_30db(){const form = document.getElementById("form")

	form.classList.remove("hidden")
	form.classList.add("block")
}`,
		Call:       templ.SafeScript(`__templ_addTodoClick_30db`),
		CallInline: templ.SafeScriptInline(`__templ_addTodoClick_30db`),
	}
}

func inputFieldChange() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_inputFieldChange_a0e5`,
		Function: `function __templ_inputFieldChange_a0e5(){const inputForm = document.getElementById("input-form")
	const addButton = document.getElementById("add-button")
	const val = inputForm.value

	if(val.length < 5) {
		addButton.setAttribute("disabled", true)
		addButton.classList.remove("hover:border-green-400", "hover:bg-green-400", "border-green-300", "bg-green-300")
		addButton.classList.add("border-green-100", "bg-green-100")
		return
	}

	addButton.classList.add("hover:border-green-400", "hover:bg-green-400", "border-green-300", "bg-green-300")
	addButton.classList.remove("border-green-100", "bg-green-100")
	addButton.removeAttribute("disabled", false)
}`,
		Call:       templ.SafeScript(`__templ_inputFieldChange_a0e5`),
		CallInline: templ.SafeScriptInline(`__templ_inputFieldChange_a0e5`),
	}
}

func cancelTodoClick() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_cancelTodoClick_a377`,
		Function: `function __templ_cancelTodoClick_a377(){const form = document.getElementById("form")

	form.classList.remove("block")
	form.classList.add("hidden")
}`,
		Call:       templ.SafeScript(`__templ_cancelTodoClick_a377`),
		CallInline: templ.SafeScriptInline(`__templ_cancelTodoClick_a377`),
	}
}

func onload() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_onload_d8d2`,
		Function: `function __templ_onload_d8d2(){const form = document.getElementById("todo-form")
	const inputForm = document.getElementById("input-form")
	const addButton = document.getElementById("add-button")

	form.addEventListener('htmx:afterRequest', e => {
		inputForm.value = ""
		addButton.setAttribute("disabled", true)
		addButton.classList.remove("hover:border-green-400", "hover:bg-green-400", "border-green-300", "bg-green-300")
		addButton.classList.add("border-green-100", "bg-green-100")
	})
}`,
		Call:       templ.SafeScript(`__templ_onload_d8d2`),
		CallInline: templ.SafeScriptInline(`__templ_onload_d8d2`),
	}
}

func Home(name string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html><head><meta charset=\"utf-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><script src=\"https://cdn.tailwindcss.com\"></script><script src=\"https://unpkg.com/htmx.org@1.9.2\" integrity=\"sha384-L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h\" crossorigin=\"anonymous\"></script><title>To Do List</title><link rel=\"stylesheet\" href=\"/static/css/globals.css\"></head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, onload())
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body onload=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.ComponentScript = onload()
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2.Call)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"w-full h-[100vh] bg-[#272727]\"><div class=\"w-full h-full flex flex-col items-center justify-center\"><form class=\"flex justify-between bg-white rounded w-[400px] px-3\"><p>Welcome back, <span class=\"font-bold text-[20px]\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal\views\Home.templ`, Line: 62, Col: 63}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span></p><button type=\"submit\">Logout</button></form><div class=\"flex flex-col bg-white rounded h-[50%] w-[400px] px-3\"><div class=\"flex justify-between items-center my-3\"><h1 class=\"text-[25px] font-bold select-none text-[#272727]\">To Do List</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, addTodoClick())
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div onclick=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 templ.ComponentScript = addTodoClick()
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4.Call)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"text-[#272727] w-[25px] h-[25px] cursor-pointer\" viewBox=\"0 0 24 24\"><path fill=\"currentColor\" d=\"M18 13h-5v5c0 .55-.45 1-1 1s-1-.45-1-1v-5H6c-.55 0-1-.45-1-1s.45-1 1-1h5V6c0-.55.45-1 1-1s1 .45 1 1v5h5c.55 0 1 .45 1 1s-.45 1-1 1\"></path></svg></div></div><div id=\"form\" class=\"hidden overflow-y-hidden h-[45px]\"><form id=\"todo-form\" class=\"flex\" hx-post=\"/todo\" hx-target=\"#todos\" hx-swap=\"beforeend\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, inputFieldChange())
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<input oninput=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 templ.ComponentScript = inputFieldChange()
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5.Call)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" id=\"input-form\" class=\"flex-1 outline-none bg-transparent border-b border-black\" name=\"description\"> <button disabled=\"true\" id=\"add-button\" class=\"select-none py-2 px-4 rounded border text-white transition-all mx-3 border-green-100 bg-green-100\" type=\"submit\">Add\r</button> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, cancelTodoClick())
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<button type=\"button\" onclick=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 templ.ComponentScript = cancelTodoClick()
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6.Call)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"select-none py-2 px-4 rounded border border-red-300 bg-red-300 text-white transition-all hover:bg-red-400 hover:border-red-400\">Cancel\r</button></form></div><div hx-get=\"/todo\" hx-trigger=\"load\" hx-target=\"#todos\" hx-swap=\"innerHTML\"></div><div id=\"todos\" class=\"scroll\"></div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
