// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.646
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func onclick() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_onclick_97ee`,
		Function: `function __templ_onclick_97ee(){const registerForm = document.getElementById("register-auth")
	const loginForm = document.getElementById("login-auth")

	registerForm.classList.remove("hidden")
	registerForm.classList.add("block")

	loginForm.classList.remove("block")
	loginForm.classList.add("hidden")
}`,
		Call:       templ.SafeScript(`__templ_onclick_97ee`),
		CallInline: templ.SafeScriptInline(`__templ_onclick_97ee`),
	}
}

func LoginForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"login-auth\" class=\"block bg-white rounded py-2 w-[400px] px-3\"><p class=\"font-medium text-center text-[20px] my-2\">Login</p><form id=\"login-form\" hx-post=\"/login\"><input name=\"login-email\" placeholder=\"Email\" type=\"email\" class=\"border-b border-black w-full py-2 px-1 outline-none my-3\"><br><input id=\"login-password\" name=\"password\" placeholder=\"Password\" type=\"password\" class=\"border-b border-black w-full py-2 px-1 outline-none\"><br><button type=\"submit\" class=\"w-full py-2 mt-3 rounded border border-black transition-all hover:text-white hover:bg-black\">Login\r</button></form><p class=\"my-3 text-center\">or</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, onclick())
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<button onclick=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.ComponentScript = onclick()
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2.Call)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"w-full py-2 mt-3 rounded border border-black transition-all hover:text-white hover:bg-black\">Register</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
