// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.646
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func RegisterForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"bg-white rounded py-2 w-[400px] px-3\"><p class=\"font-medium text-center text-[20px] my-2\">Register</p><form id=\"register-form\" hx-post=\"/register\"><input name=\"name\" placeholder=\"Name\" type=\"text\" class=\"border-b border-black w-full py-2 px-1 outline-none\"><br><input name=\"email\" placeholder=\"Email\" type=\"email\" class=\"border-b border-black w-full py-2 px-1 outline-none my-3\"><br><input id=\"password\" name=\"password\" placeholder=\"Password\" type=\"password\" class=\"border-b border-black w-full py-2 px-1 outline-none\"><br><input id=\"confirm-password\" placeholder=\"Confirm Password\" type=\"password\" class=\"mt-3 border-b border-black w-full py-2 px-1 outline-none\"><br><button type=\"submit\" class=\"w-full py-2 mt-3 rounded border border-black transition-all hover:text-white hover:bg-black\">Register\r</button></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
